import type { Metadata } from "next";
import { Provider } from "@/store/provider/ChakraProvider";
import { quicksand } from "../public/fonts/font";

export const metadata: Metadata = {
  title: "AccountForm Information Visualization Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={quicksand.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
